### ISSUE TITLE
Browser tab is opened but app is not loaded

### ISSUE THREAD

**Issue by tomastrajan** [baldore/open-browser-webpack-plugin#1]
I am using `open-browser-webpack-plugin` but when the tab is opened the content is not loaded.
I don't see any errors in browser console, no error in command line during webpack build...

Works perfectly when I open browser manually without plugin.

![bug](https://cloud.githubusercontent.com/assets/3764868/10564450/24c93e4e-75b5-11e5-844e-f3a436049bcd.png)

## My configuration

```
plugins: [
    new OpenBrowserPlugin({ url: 'http://localhost:8081/webpack-dev-server/index.html' })
]
```

**Comment by baldore** [comment]
Can you share a configuration where I can check the error? I cannot reproduce it.

**Comment by tomastrajan** [comment]
Hmm I am now using it in different project and it works fine, I will try it in the previous one again to try to reproduce it again.

**Comment by baldore** [comment]
Closing due inactivity.
