### ISSUE TITLE
Server hangs after browser open

### ISSUE THREAD

**Issue by evandavis** [baldore/open-browser-webpack-plugin#11]
I'm using this alongside [React Storybook](https://github.com/kadirahq/react-storybook) to open `localhost:9001` on build. 

[Their `webpack.config` can be seen here.](https://github.com/kadirahq/react-storybook/blob/master/src/server/config/webpack.config.js)

I am extending it with the following simple config:

``` javascript
const OpenBrowserPlugin = require('open-browser-webpack-plugin');

module.exports = {
  plugins: [
    new OpenBrowserPlugin({url: 'http://localhost:9001/'})
  ]
};
```

The browser opens correctly, but the server just hangs, waiting for localhost forever. If I start the app _without_ this plugin, I am able to browse to `localhost:9001` manually and the server works fine.

**Comment by evandavis** [comment]
I can confirm it's this line that breaks things:
```javascript
removeFromArray(stats.compilation.compiler._plugins['done'], doneCallback);

**Comment by baldore** [comment]
lol, that's weird. I can't check it right now, but I'll debug it when I have some time.

**Comment by plemarquand** [comment]
@evandavis @baldore I think my patch should resolve this issue for you. I'm using my branch locally without issue with `react-storybook`.
